/**
 * Centralized error IDs for tracking and monitoring
 * Use these IDs in error logs for Sentry/error tracking integration
 */

export const ERROR_IDS = {
  // Audit Logging Errors
  AUDIT_LOG_FAILED: 'AUDIT_LOG_FAILED',
  AUDIT_LOG_FAILED_ON_DELETE: 'AUDIT_LOG_FAILED_ON_DELETE',
  AUDIT_LOG_FAILED_ON_CREATE: 'AUDIT_LOG_FAILED_ON_CREATE',
  AUDIT_LOG_FAILED_ON_UPDATE: 'AUDIT_LOG_FAILED_ON_UPDATE',
  AUDIT_AUTH_CHECK_FAILED: 'AUDIT_AUTH_CHECK_FAILED',
  AUDIT_LOGS_FETCH_FAILED: 'AUDIT_LOGS_FETCH_FAILED',

  // Authentication Errors
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',

  // Database Errors
  DB_CONNECTION_FAILED: 'DB_CONNECTION_FAILED',
  DB_QUERY_FAILED: 'DB_QUERY_FAILED',
  DB_TRANSACTION_FAILED: 'DB_TRANSACTION_FAILED',

  // Validation Errors
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_DATE_FORMAT: 'INVALID_DATE_FORMAT',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',

  // API Errors
  API_REQUEST_FAILED: 'API_REQUEST_FAILED',
  API_RATE_LIMIT: 'API_RATE_LIMIT',

  // User Management Errors
  USER_CREATE_FAILED: 'USER_CREATE_FAILED',
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',
  USER_DELETE_FAILED: 'USER_DELETE_FAILED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Project Errors
  PROJECT_CREATE_FAILED: 'PROJECT_CREATE_FAILED',
  PROJECT_UPDATE_FAILED: 'PROJECT_UPDATE_FAILED',
  PROJECT_DELETE_FAILED: 'PROJECT_DELETE_FAILED',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',

  // Data Operations
  DATA_CLEAR_FAILED: 'DATA_CLEAR_FAILED',
  ANALYTICS_CLEAR_FAILED: 'ANALYTICS_CLEAR_FAILED',
  BULK_OPERATION_FAILED: 'BULK_OPERATION_FAILED',

  // System Errors
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorId = (typeof ERROR_IDS)[keyof typeof ERROR_IDS];
